
runtime: python37
env: standard
instance_class: F1
handlers:
  - url: '/retweet/.*'
    script: auto
    # login: required
    secure: always
automatic_scaling:
  max_instances: 1
  max_concurrent_requests: 2
